### PR TITLE
Tune About page member lists

### PR DESCRIPTION
**Pull request by smoya**
- Lists alphabetically-ordered
- No roles for Distinguished members (hard to maintain).
- Added slack users to Distinguished members.
- Adapted staff members format to be consistent with the Distinguished members list.

### CODE REVIEW

**Comment by KoeSystems** [comment]
🚀

**Comment by sdecandelario** [comment]
Maybe the staff members without position?

**Comment by smoya** [comment]
I kept the position there because is gonna be easy to maintain as the list is super short. I think it adds some value.

**Comment by sdecandelario** [comment]
Okey, I only commented to maitain the same format, but the staff members are easy to maintain, so for mi it's key!

**Pull request merged**
